### ISSUE TITLE
`Psych::DisallowedClass` error when running `YAML.safe_load`

### ISSUE THREAD

**Issue by kwkwan** [lutaml/expressir#173]
Trace:

```
 Failure/Error:
       ::Lutaml::Parser
         .parse(File.new(path), ::Lutaml::Parser::EXPRESS_CACHE_PARSE_TYPE)
     
     Psych::DisallowedClass:
       asciidoctor: FAILED: test.adoc: Failed to load AsciiDoc document - Tried to load unspecified class: Symbol
     # ./lib/metanorma/plugin/lutaml/utils.rb:110:in `load_express_repo_from_cache'
     # ./lib/metanorma/plugin/lutaml/utils.rb:73:in `load_express_repositories'
     # ./lib/metanorma/plugin/lutaml/utils.rb:177:in `block in parse_document_express_indexes'
     # ./lib/metanorma/plugin/lutaml/utils.rb:160:in `loop'
     # ./lib/metanorma/plugin/lutaml/utils.rb:160:in `parse_document_express_indexes'
     # ./lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb:26:in `process'
     # ./spec/spec_helper.rb:102:in `metanorma_process'
     # ./spec/metanorma/plugin/lutaml/lutaml_text_preprocessor_spec.rb:328:in `block (7 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Psych::DisallowedClass:
     #   Tried to load unspecified class: Symbol
     #   ./lib/metanorma/plugin/lutaml/utils.rb:110:in `load_express_repo_from_cache'
```

**Comment by kwkwan** [comment]
The YAML file looks like:

```
---
_class: Expressir::Model::Cache
version: 2.1.3
content:
  _class: Expressir::Model::Repository
  schemas:
  - _class: Expressir::Model::Declarations::Schema
    file: spec/fixtures/lutaml/expressir_relative_paths/test_relative_includes.exp
    id: annotated_3d_model_data_quality_criteria_schema
    remarks:
    - |-
      My text

      link:downloads/report.pdf[Get Report]

      link:http://test.com/include1.csv[]

      include::include1.csv[]

      include::test/include1.csv[]
      include::http://test.com/include1.csv[]
    version:
     _class: Expressir::Model::Declarations::SchemaVersion
     value: "{iso standard 10303 part(59) version(3) object(1) annotated_3d_model_data_quality_criteria_schema(6)}"
     items:
      - _class: Expressir::Model::Declarations::SchemaVersionItem
        name: iso
      - _class: Expressir::Model::Declarations::SchemaVersionItem
        name: standard
      - _class: Expressir::Model::Declarations::SchemaVersionItem
        value: '10303'
      - _class: Expressir::Model::Declarations::SchemaVersionItem
        name: part
        value: '59'
      - _class: Expressir::Model::Declarations::SchemaVersionItem
        name: version
        value: '3'
      - _class: Expressir::Model::Declarations::SchemaVersionItem
        name: object
        value: '1'
      - _class: Expressir::Model::Declarations::SchemaVersionItem
        name: annotated_3d_model_data_quality_criteria_schema
        value: '6'
    interfaces:
    - _class: Expressir::Model::Declarations::Interface
      kind: :REFERENCE
      schema:
        _class: Expressir::Model::References::SimpleReference
        id: measure_schema
      items:
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: measure_value
    - _class: Expressir::Model::Declarations::Interface
      kind: :REFERENCE
      schema:
        _class: Expressir::Model::References::SimpleReference
        id: product_data_quality_criteria_schema
      items:
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: data_quality_criteria_representation
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: data_quality_criterion
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: data_quality_measurement_requirement
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: detailed_report_request_with_number_of_data
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: summary_report_request
    - _class: Expressir::Model::Declarations::Interface
      kind: :REFERENCE
      schema:
        _class: Expressir::Model::References::SimpleReference
        id: representation_schema
      items:
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: representation
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: representation_item
    - _class: Expressir::Model::Declarations::Interface
      kind: :REFERENCE
      schema:
        _class: Expressir::Model::References::SimpleReference
        id: shape_data_quality_criteria_schema
      items:
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: shape_data_quality_assessment_specification_select
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: shape_measurement_accuracy
    - _class: Expressir::Model::Declarations::Interface
      kind: :REFERENCE
      schema:
        _class: Expressir::Model::References::SimpleReference
        id: support_resource_schema
      items:
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: identifier
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: label
      - _class: Expressir::Model::Declarations::InterfaceItem
        ref:
          _class: Expressir::Model::References::SimpleReference
          id: text
    types:
    - _class: Expressir::Model::Declarations::Type
      id: a3m_accuracy_associated_target_select
      underlying_type:
        _class: Expressir::Model::DataTypes::Select
        extensible: true
    - _class: Expressir::Model::Declarations::Type
      id: a3m_data_quality_accuracy_type_name
      underlying_type:
        _class: Expressir::Model::DataTypes::Enumeration
        extensible: true
    - _class: Expressir::Model::Declarations::Type
      id: a3m_data_quality_inspected_element_type_name
      underlying_type:
        _class: Expressir::Model::DataTypes::Enumeration
        extensible: true
    - _class: Expressir::Model::Declarations::Type
      id: a3m_data_quality_measured_data_type_name
      underlying_type:
        _class: Expressir::Model::DataTypes::Enumeration
        extensible: true
    - _class: Expressir::Model::Declarations::Type
      id: a3m_data_quality_type_name_for_location_of_extreme_value
      underlying_type:
        _class: Expressir::Model::DataTypes::Enumeration
        extensible: true
    - _class: Expressir::Model::Declarations::Type
      id: summary_stats_value_type
      underlying_type:
        _class: Expressir::Model::DataTypes::Enumeration
        items:
        - _class: Expressir::Model::DataTypes::EnumerationItem
          id: average_value
        - _class: Expressir::Model::DataTypes::EnumerationItem
          id: max_value
        - _class: Expressir::Model::DataTypes::EnumerationItem
          id: min_value
    entities:
    - _class: Expressir::Model::Declarations::Entity
      id: a3m_data_quality_criteria_representation
      subtype_of:
      - _class: Expressir::Model::References::SimpleReference
        id: data_quality_criteria_representation
      where_rules:
      - _class: Expressir::Model::Declarations::WhereRule
        id: WR1
        expression:
          _class: Expressir::Model::Expressions::BinaryExpression
          operator: :GREATER_THAN
          operand1:
            _class: Expressir::Model::Expressions::FunctionCall
            function:
              _class: Expressir::Model::References::SimpleReference
              id: SIZEOF
            parameters:
            - _class: Expressir::Model::Expressions::QueryExpression
              id: q
              aggregate_source:
                _class: Expressir::Model::References::AttributeReference
                ref:
                  _class: Expressir::Model::References::GroupReference
                  ref:
                    _class: Expressir::Model::References::SimpleReference
                    id: SELF
                  entity:
                    _class: Expressir::Model::References::SimpleReference
                    id: representation
                attribute:
                  _class: Expressir::Model::References::SimpleReference
                  id: items
              expression:
                _class: Expressir::Model::Expressions::BinaryExpression
                operator: :IN
                operand1:
                  _class: Expressir::Model::Expressions::BinaryExpression
                  operator: :ADDITION
                  operand1:
                    _class: Expressir::Model::Literals::String
                    value: ANNOTATED_3D_MODEL_DATA_QUALITY_CRITERIA_SCHEMA.
                  operand2:
                    _class: Expressir::Model::Literals::String
                    value: A3M_DATA_QUALITY_CRITERION
                operand2:
                  _class: Expressir::Model::Expressions::FunctionCall
                  function:
                    _class: Expressir::Model::References::SimpleReference
                    id: TYPEOF
                  parameters:
                  - _class: Expressir::Model::Expressions::FunctionCall
                    function:
                      _class: Expressir::Model::References::SimpleReference
                      id: q
          operand2:
            _class: Expressir::Model::Literals::Integer
            value: '0'
    - _class: Expressir::Model::Declarations::Entity
      id: a3m_data_quality_criterion
      abstract: true
      subtype_of:
      - _class: Expressir::Model::References::SimpleReference
        id: data_quality_criterion
      - _class: Expressir::Model::References::SimpleReference
        id: data_quality_measurement_requirement
      attributes:
      - _class: Expressir::Model::Declarations::Attribute
        id: assessment_specification
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: shape_data_quality_assessment_specification_select
      - _class: Expressir::Model::Declarations::Attribute
        id: measured_data_type
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: a3m_data_quality_measured_data_type_name
          base_path: annotated_3d_model_data_quality_criteria_schema.a3m_data_quality_measured_data_type_name
      - _class: Expressir::Model::Declarations::Attribute
        id: inspected_elements_types
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::DataTypes::List
          bound1:
            _class: Expressir::Model::Literals::Integer
            value: '1'
          bound2:
            _class: Expressir::Model::References::SimpleReference
            id: "?"
          base_type:
            _class: Expressir::Model::References::SimpleReference
            id: a3m_data_quality_inspected_element_type_name
            base_path: annotated_3d_model_data_quality_criteria_schema.a3m_data_quality_inspected_element_type_name
      - _class: Expressir::Model::Declarations::Attribute
        id: accuracy_types
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::DataTypes::List
          bound1:
            _class: Expressir::Model::Literals::Integer
            value: '0'
          bound2:
            _class: Expressir::Model::References::SimpleReference
            id: "?"
          base_type:
            _class: Expressir::Model::References::SimpleReference
            id: a3m_data_quality_accuracy_type_name
            base_path: annotated_3d_model_data_quality_criteria_schema.a3m_data_quality_accuracy_type_name
      - _class: Expressir::Model::Declarations::Attribute
        id: location_of_extreme_value_types
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::DataTypes::List
          bound1:
            _class: Expressir::Model::Literals::Integer
            value: '0'
          bound2:
            _class: Expressir::Model::References::SimpleReference
            id: "?"
          base_type:
            _class: Expressir::Model::References::SimpleReference
            id: a3m_data_quality_type_name_for_location_of_extreme_value
            base_path: annotated_3d_model_data_quality_criteria_schema.a3m_data_quality_type_name_for_location_of_extreme_value
    - _class: Expressir::Model::Declarations::Entity
      id: a3m_data_quality_criterion_specific_applied_value
      abstract: true
      subtype_of:
      - _class: Expressir::Model::References::SimpleReference
        id: representation_item
      attributes:
      - _class: Expressir::Model::Declarations::Attribute
        id: criterion_to_assign_the_value
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: a3m_data_quality_criterion
          base_path: annotated_3d_model_data_quality_criteria_schema.a3m_data_quality_criterion
      - _class: Expressir::Model::Declarations::Attribute
        id: applied_value
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: measure_value
    - _class: Expressir::Model::Declarations::Entity
      id: a3m_data_quality_target_accuracy_association
      attributes:
      - _class: Expressir::Model::Declarations::Attribute
        id: id
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: identifier
      - _class: Expressir::Model::Declarations::Attribute
        id: name
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: label
      - _class: Expressir::Model::Declarations::Attribute
        id: description
        kind: :EXPLICIT
        optional: true
        type:
          _class: Expressir::Model::References::SimpleReference
          id: text
      - _class: Expressir::Model::Declarations::Attribute
        id: accuracy_specification
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: shape_measurement_accuracy
      - _class: Expressir::Model::Declarations::Attribute
        id: target_to_associate
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: a3m_accuracy_associated_target_select
          base_path: annotated_3d_model_data_quality_criteria_schema.a3m_accuracy_associated_target_select
    - _class: Expressir::Model::Declarations::Entity
      id: a3m_detailed_report_request
      subtype_of:
      - _class: Expressir::Model::References::SimpleReference
        id: detailed_report_request_with_number_of_data
      attributes:
      - _class: Expressir::Model::Declarations::Attribute
        id: value_type_requested
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: summary_stats_value_type
          base_path: annotated_3d_model_data_quality_criteria_schema.summary_stats_value_type
    - _class: Expressir::Model::Declarations::Entity
      id: a3m_summary_report_request_with_representative_value
      subtype_of:
      - _class: Expressir::Model::References::SimpleReference
        id: summary_report_request
      attributes:
      - _class: Expressir::Model::Declarations::Attribute
        id: value_type_requested
        kind: :EXPLICIT
        type:
          _class: Expressir::Model::References::SimpleReference
          id: summary_stats_value_type
          base_path: annotated_3d_model_data_quality_criteria_schema.summary_stats_value_type
```
