### ISSUE TITLE
Invalid spec fixtures or `expression` can contains models other than `Expressir::Model::Expressions::XXX`?

### ISSUE THREAD

**Issue by kwkwan** [lutaml/expressir#233]
Hi @ronaldtse, some spec fixtures seem invalid.

For example, in the yaml file https://raw.githubusercontent.com/lutaml/expressir/refs/heads/main/spec/syntax/mathematical_functions_schema.yaml (line 11457), the model `Expressir::Model::Statements::Return` contains `expression` with `_class` like `Expressir::Model::Literals::Logical`.

```
statements:
  - _class: Expressir::Model::Statements::Return
    expression:
      _class: Expressir::Model::Literals::Logical
      value: :FALSE
```

It seems that the values of `expression` are not correct.  It is because `expression` should have `_class` like `Expressir::Model::Expressions::XXX`, but not `Expressir::Model::Literals::Logical`.
